var annotated_dup =
[
    [ "rapidfuzz", "namespacerapidfuzz.html", [
      [ "common", "namespacerapidfuzz_1_1common.html", [
        [ "PatternMatchVector", "structrapidfuzz_1_1common_1_1PatternMatchVector.html", "structrapidfuzz_1_1common_1_1PatternMatchVector" ],
        [ "BlockPatternMatchVector", "structrapidfuzz_1_1common_1_1BlockPatternMatchVector.html", "structrapidfuzz_1_1common_1_1BlockPatternMatchVector" ],
        [ "CharHashTable", "structrapidfuzz_1_1common_1_1CharHashTable.html", "structrapidfuzz_1_1common_1_1CharHashTable" ],
        [ "CharHashTable< CharT1, ValueType, 1 >", "structrapidfuzz_1_1common_1_1CharHashTable_3_01CharT1_00_01ValueType_00_011_01_4.html", "structrapidfuzz_1_1common_1_1CharHashTable_3_01CharT1_00_01ValueType_00_011_01_4" ],
        [ "MatrixVectorView", "structrapidfuzz_1_1common_1_1MatrixVectorView.html", "structrapidfuzz_1_1common_1_1MatrixVectorView" ],
        [ "ConstMatrixVectorView", "structrapidfuzz_1_1common_1_1ConstMatrixVectorView.html", "structrapidfuzz_1_1common_1_1ConstMatrixVectorView" ],
        [ "Matrix", "structrapidfuzz_1_1common_1_1Matrix.html", "structrapidfuzz_1_1common_1_1Matrix" ]
      ] ],
      [ "detail", "namespacerapidfuzz_1_1detail.html", [
        [ "difflib", "namespacerapidfuzz_1_1detail_1_1difflib.html", [
          [ "SequenceMatcher", "classrapidfuzz_1_1detail_1_1difflib_1_1SequenceMatcher.html", "classrapidfuzz_1_1detail_1_1difflib_1_1SequenceMatcher" ]
        ] ],
        [ "LLCSBitMatrix", "structrapidfuzz_1_1detail_1_1LLCSBitMatrix.html", "structrapidfuzz_1_1detail_1_1LLCSBitMatrix" ],
        [ "LevenshteinBitMatrix", "structrapidfuzz_1_1detail_1_1LevenshteinBitMatrix.html", "structrapidfuzz_1_1detail_1_1LevenshteinBitMatrix" ],
        [ "MatchingBlock", "structrapidfuzz_1_1detail_1_1MatchingBlock.html", "structrapidfuzz_1_1detail_1_1MatchingBlock" ]
      ] ],
      [ "fuzz", "namespacerapidfuzz_1_1fuzz.html", [
        [ "CachedRatio", "structrapidfuzz_1_1fuzz_1_1CachedRatio.html", "structrapidfuzz_1_1fuzz_1_1CachedRatio" ],
        [ "CachedPartialRatio", "structrapidfuzz_1_1fuzz_1_1CachedPartialRatio.html", "structrapidfuzz_1_1fuzz_1_1CachedPartialRatio" ],
        [ "CachedTokenSortRatio", "structrapidfuzz_1_1fuzz_1_1CachedTokenSortRatio.html", "structrapidfuzz_1_1fuzz_1_1CachedTokenSortRatio" ],
        [ "CachedPartialTokenSortRatio", "structrapidfuzz_1_1fuzz_1_1CachedPartialTokenSortRatio.html", "structrapidfuzz_1_1fuzz_1_1CachedPartialTokenSortRatio" ],
        [ "CachedTokenSetRatio", "structrapidfuzz_1_1fuzz_1_1CachedTokenSetRatio.html", "structrapidfuzz_1_1fuzz_1_1CachedTokenSetRatio" ],
        [ "CachedPartialTokenSetRatio", "structrapidfuzz_1_1fuzz_1_1CachedPartialTokenSetRatio.html", "structrapidfuzz_1_1fuzz_1_1CachedPartialTokenSetRatio" ],
        [ "CachedTokenRatio", "structrapidfuzz_1_1fuzz_1_1CachedTokenRatio.html", "structrapidfuzz_1_1fuzz_1_1CachedTokenRatio" ],
        [ "CachedPartialTokenRatio", "structrapidfuzz_1_1fuzz_1_1CachedPartialTokenRatio.html", "structrapidfuzz_1_1fuzz_1_1CachedPartialTokenRatio" ],
        [ "CachedWRatio", "structrapidfuzz_1_1fuzz_1_1CachedWRatio.html", "structrapidfuzz_1_1fuzz_1_1CachedWRatio" ],
        [ "CachedQRatio", "structrapidfuzz_1_1fuzz_1_1CachedQRatio.html", "structrapidfuzz_1_1fuzz_1_1CachedQRatio" ]
      ] ],
      [ "IteratorView", "classrapidfuzz_1_1IteratorView.html", "classrapidfuzz_1_1IteratorView" ],
      [ "StringAffix", "structrapidfuzz_1_1StringAffix.html", "structrapidfuzz_1_1StringAffix" ],
      [ "LevenshteinWeightTable", "structrapidfuzz_1_1LevenshteinWeightTable.html", "structrapidfuzz_1_1LevenshteinWeightTable" ],
      [ "EditOp", "structrapidfuzz_1_1EditOp.html", "structrapidfuzz_1_1EditOp" ],
      [ "Opcode", "structrapidfuzz_1_1Opcode.html", "structrapidfuzz_1_1Opcode" ],
      [ "Editops", "classrapidfuzz_1_1Editops.html", "classrapidfuzz_1_1Editops" ],
      [ "Opcodes", "classrapidfuzz_1_1Opcodes.html", "classrapidfuzz_1_1Opcodes" ],
      [ "satisfies_all", "structrapidfuzz_1_1satisfies__all.html", null ],
      [ "satisfies_all< Cond, Conds... >", "structrapidfuzz_1_1satisfies__all_3_01Cond_00_01Conds_8_8_8_01_4.html", null ],
      [ "satisfies_any", "structrapidfuzz_1_1satisfies__any.html", null ],
      [ "satisfies_any< Cond, Conds... >", "structrapidfuzz_1_1satisfies__any_3_01Cond_00_01Conds_8_8_8_01_4.html", null ],
      [ "is_explicitly_convertible", "structrapidfuzz_1_1is__explicitly__convertible.html", null ],
      [ "is_hashable_sequence", "classrapidfuzz_1_1is__hashable__sequence.html", null ],
      [ "is_standard_iterable", "classrapidfuzz_1_1is__standard__iterable.html", null ],
      [ "has_bracket_operator", "classrapidfuzz_1_1has__bracket__operator.html", null ],
      [ "SplittedSentenceView", "classrapidfuzz_1_1SplittedSentenceView.html", "classrapidfuzz_1_1SplittedSentenceView" ],
      [ "DecomposedSet", "structrapidfuzz_1_1DecomposedSet.html", "structrapidfuzz_1_1DecomposedSet" ],
      [ "is_space_dispatch_tag", "structrapidfuzz_1_1is__space__dispatch__tag.html", null ],
      [ "is_space_dispatch_tag< CharT, typename std::enable_if< sizeof(CharT)==1 >::type >", "structrapidfuzz_1_1is__space__dispatch__tag_3_01CharT_00_01typename_01std_1_1enable__if_3_01size74eea1ad531ee41dd15e9a4ebb774b98.html", null ],
      [ "CachedHamming", "structrapidfuzz_1_1CachedHamming.html", "structrapidfuzz_1_1CachedHamming" ],
      [ "CachedIndel", "structrapidfuzz_1_1CachedIndel.html", "structrapidfuzz_1_1CachedIndel" ],
      [ "CachedLevenshtein", "structrapidfuzz_1_1CachedLevenshtein.html", "structrapidfuzz_1_1CachedLevenshtein" ]
    ] ],
    [ "ag", "structag.html", "structag" ],
    [ "arcdps_exports", "structarcdps__exports.html", "structarcdps__exports" ],
    [ "BaseSingleton", "classBaseSingleton.html", "classBaseSingleton" ],
    [ "cbtevent", "structcbtevent.html", "structcbtevent" ],
    [ "CombatEventHandler", "classCombatEventHandler.html", "classCombatEventHandler" ],
    [ "ComponentBase", "classComponentBase.html", "classComponentBase" ],
    [ "DemoKeyBindComponent", "classDemoKeyBindComponent.html", "classDemoKeyBindComponent" ],
    [ "DemoPositioningComponent", "classDemoPositioningComponent.html", "classDemoPositioningComponent" ],
    [ "DemoTable", "classDemoTable.html", "classDemoTable" ],
    [ "DemoTableWindow", "classDemoTableWindow.html", "classDemoTableWindow" ],
    [ "DemoWindow", "classDemoWindow.html", "classDemoWindow" ],
    [ "EventSequencer", "classEventSequencer.html", "classEventSequencer" ],
    [ "IconLoader", "classIconLoader.html", "classIconLoader" ],
    [ "IconLoaderTests", "classIconLoaderTests.html", null ],
    [ "Identity", "structIdentity.html", "structIdentity" ],
    [ "InputTextCallback_UserData", "structInputTextCallback__UserData.html", "structInputTextCallback__UserData" ],
    [ "KeyBindComponent", "classKeyBindComponent.html", "classKeyBindComponent" ],
    [ "KeyBindHandler", "classKeyBindHandler.html", "classKeyBindHandler" ],
    [ "LinkedMem", "structLinkedMem.html", "structLinkedMem" ],
    [ "Localization", "classLocalization.html", "classLocalization" ],
    [ "MainTable", "classMainTable.html", "classMainTable" ],
    [ "MainTableColumn", "structMainTableColumn.html", "structMainTableColumn" ],
    [ "MainWindow", "classMainWindow.html", "classMainWindow" ],
    [ "MumbleContext", "structMumbleContext.html", "structMumbleContext" ],
    [ "PositioningComponent", "classPositioningComponent.html", "classPositioningComponent" ],
    [ "PositioningComponentImGuiHook", "classPositioningComponentImGuiHook.html", null ],
    [ "RingBuffer", "classRingBuffer.html", "classRingBuffer" ],
    [ "Row", "structRow.html", "structRow" ],
    [ "SimpleNetworkStack", "classSimpleNetworkStack.html", "classSimpleNetworkStack" ],
    [ "SimpleNetworkStackTests", "classSimpleNetworkStackTests.html", "classSimpleNetworkStackTests" ],
    [ "Singleton", "classSingleton.html", "classSingleton" ],
    [ "SingletonManager", "classSingletonManager.html", "classSingletonManager" ],
    [ "UpdateChecker", "classUpdateChecker.html", "classUpdateChecker" ],
    [ "UpdateCheckerBase", "classUpdateCheckerBase.html", "classUpdateCheckerBase" ]
];