name: CMake

on: push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      # install cmake and ninja
      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          # This specifies the location of vcpkg, where it is going to be restored from cache, or create from scratch.
          # vcpkgDirectory: '${{ github.workspace }}/vcpkg'

          # The Git commit id of vcpkg to be checked out. This is only needed because we are not using a submodule.
          vcpkgGitCommitId: '9c7c66471005cb132832786d5d65d83d2cf503ad'

          # The vcpkg.json file, which will be part of cache key computation.
#          vcpkgJsonGlob: '${{ github.workspace }}/vcpkg.json'

          # don't run vcpkg install in the project, ket run-cmake do it.
          runVcpkgInstall: false

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          # cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: debug
          buildPreset: debug

      - name: Run Test
        run: '${sourceDir}/cmake-build/debug/ArcdpsExtensionTests.exe'
